name: voxxedapp
description: Displays details about upcoming Voxxed Days

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0

environment:
  sdk: ^2.0.0

dependencies:
  flutter:
    sdk: flutter

  #built_collection: '>=2.0.0 <4.0.0'
  built_value: ^7.0.0
  cached_network_image: ^2.0.0-rc
#  collection: ^1.14.12
  flutter_local_notifications: ^0.9.1
  logging: ^0.11.3+2
  path_provider: ^1.5.1
  rebloc: ^0.3.0+1
  url_launcher: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build: ^1.2.2
  build_runner: ^1.7.2
  built_value_generator: ^7.0.0
  source_gen: ^0.9.4+6

  flutter_launcher_icons: ^0.7.4

flutter:
  uses-material-design: true

  assets:
    - assets/json/cold_boot.json

  fonts:
  - family: Lato
    fonts:
    - asset: assets/font/Lato-Regular.ttf
    - asset: assets/font/Lato-Italic.ttf
      style: italic
    - asset: assets/font/Lato-Bold.ttf
      weight: 700
    - asset: assets/font/Lato-BoldItalic.ttf
      weight: 700
      style: italic

# This is the config for flutter_launcher_icons, which
# generates iOS and Android launcher icons from a source image.
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/launcher_icon.jpg"
